services:
  ntfy:
    image: binwiederhier/ntfy
    command: serve
    environment:
      NTFY_BASE_URL: https://ntfy.nettradar.no
      NTFY_LISTEN_HTTP: :80
      NTFY_UPSTREAM_BASE_URL: https://ntfy.sh
      NTFY_CACHE_FILE: /var/cache/ntfy/cache.db
      NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
    volumes:
      - ntfy-cache:/var/cache/ntfy
      - ntfy-data:/var/lib/ntfy
    ports:
      - "127.0.0.1:2586:80"
    restart: always

volumes:
  ntfy-cache:
  ntfy-data:
